name: Deployment to production

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

# Allow only one concurrent deployment.
concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy-to-production:
    name: Deploy to production
    uses: ./.github/workflows/deployment.yml
    with:
      target-name: Production
      target-url: https://dassencio.org
    secrets:
      ssh-deploy-key: ${{secrets.SSH_DEPLOY_KEY}}
      ssh-known-hosts: ${{secrets.SSH_KNOWN_HOSTS}}
      rsync-destination: ${{secrets.RSYNC_DST_PRODUCTION}}
