name: Deployment

on:
  workflow_call:
    inputs:
      target-name:
        description: "Name of deployment target"
        type: string
        required: true
      target-url:
        description: "URL of deployment target"
        type: string
        required: true
    secrets:
      ssh-deploy-key:
        description: "Private SSH key used to deploy the website"
        required: true
      ssh-known-hosts:
        description: "SSH known-host list for automatic host verification"
        required: true
      rsync-destination:
        description: "Rsync destination (user@host:/path)"
        required: true

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.target-name}}
      url: ${{inputs.target-url}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy website
        run: |
          mkdir -p $HOME/.ssh
          echo "LogLevel ERROR" > $HOME/.ssh/config
          echo "${{secrets.ssh-deploy-key}}" > $HOME/.ssh/id_rsa
          echo "${{secrets.ssh-known-hosts}}" > $HOME/.ssh/known_hosts
          chmod 600 $HOME/.ssh/id_rsa
          rsync -azv --delete ./dist/ "${{secrets.rsync-destination}}"
